apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: suzuki3182-dev
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: keycloak
          image: ghcr.io/iqgeo/utils-keycloak-iqgeo/keycloak:latest
          command:
            - /opt/keycloak/bin/kc.sh
          args:
            - start-dev
            - --import-realm
          ports:
            - containerPort: 8080
          env:
            - name: KC_HOSTNAME
              value: keycloak.apps.rm2.thpm.p1.openshiftapps.com
            - name: KC_HTTP_PORT
              value: "8080"
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KC_PROXY
              value: edge
            - name: IQGEO_DOMAIN
              value: https://iqgeo-platform.apps.rm2.thpm.p1.openshiftapps.com
            - name: IQGEO_CLIENT_SECRET
              value: qpyu1mCm8zvvKTXRnKxwap1A6xMChuY6
            - name: SSL_REQUIRED
              value: none
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: suzuki3182-dev
  labels:
    app: keycloak
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: keycloak
